import { writeFile } from 'node:fs/promises';
import { dashboardApiContracts } from '../src/shared/api-contracts';

const routes = Object.fromEntries(
  Object.entries(dashboardApiContracts).map(([key, contract]) => [
    key,
    { method: contract.method, path: contract.path },
  ]),
);

const source = `// Generated by scripts/generate-cli-api-routes.ts. Do not edit.\n\n`
  + `import type { DashboardApiContractKey } from '../../shared/api-contracts';\n`
  + `import type { HttpMethod } from '../../shared/contracts/api-contracts-common';\n\n`
  + `export const cliApiRoutes = ${JSON.stringify(routes, null, 2)} as const satisfies Record<\n`
  + `  DashboardApiContractKey,\n`
  + `  { method: HttpMethod; path: string }\n`
  + `>;\n`;

await writeFile(
  new URL('../src/cli/lib/api-routes.generated.ts', import.meta.url),
  source,
  'utf8',
);
